branch-defaults:
  master:
    environment: youtunes-env
environment-defaults:
  youtunes-env:
    branch: null
    repository: null
global:
  application_name: youtunes
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-1::platform/Python 2.7 running
    on 64bit Amazon Linux/2.5.2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
